In [66]:
import numpy as np
from numpy import log,dot,e,shape
import matplotlib.pyplot as plt

In [67]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [68]:
X,y=make_classification(n_features=4,n_classes=2)

In [69]:
np.shape(X)

(100, 4)

In [70]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

In [71]:
np.shape(x_train)

(90, 4)

In [72]:
#standardizattion:
def standardize(x_train):
  for i in range(np.shape(x_train)[1]): #because data is 2 demensional so we have to add [1].
    x_train[:,i]=(x_train[:,i]-np.mean(x_train[:,i])) / np.std(x_train[:,i])

In [73]:
w=np.zeros((np.shape(X)[1]+1,1))
print(w)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [74]:
np.shape(X)[1]

4

In [75]:
temp_x=np.c_[np.ones((np.shape(X)[0],1)),X]
print(temp_x)

[[ 1.          0.95399145  1.12901607 -0.48828223  0.99293465]
 [ 1.         -1.11694139 -1.73963894  1.17730081  0.56999654]
 [ 1.         -1.07113362 -1.19160135  0.43799831 -1.43023359]
 [ 1.          0.25793033  0.56174934 -0.50383934 -0.79524308]
 [ 1.         -0.3505425  -0.2467888  -0.06421267 -1.06182696]
 [ 1.          0.7004756   0.7524453  -0.2475665   1.0464977 ]
 [ 1.          0.16180519  0.4029223  -0.38931086 -0.70840128]
 [ 1.          1.21696828  2.23736304 -1.77840256 -2.03904292]
 [ 1.         -0.81678341 -1.41745977  1.07157679  1.01945612]
 [ 1.          0.55870263  0.48118217 -0.02499709  1.32807037]
 [ 1.         -0.03155714  0.00536104 -0.04575795 -0.20995582]
 [ 1.         -0.96667871 -1.13264673  0.47827316 -1.0533507 ]
 [ 1.          0.40077393  0.53727505 -0.29641484  0.15598386]
 [ 1.          1.67035313  2.23607567 -1.23077997  0.66333895]
 [ 1.         -1.14539799 -1.7396115   1.14300675  0.40060344]
 [ 1.          0.78971731  1.73175492 -1.55976396 -2.48

In [76]:
class LogidticRegression:
#initialize:
  def initialize(self,X):
    weights=np.zeros((np.shape(X)[1]+1,1)) # feature vectors
    X = np.c_[np.ones((np.shape(X)[0],1)),X]  #add a bias column of ones to our feature vectors matrix
    return weights,X
#sigmoid:
  def sigmoid(self,z):
    sig=1/(1+np.e**(-z))
    return sig
#Gradient Descent:
  def fit(self,X,y,alpha=0.001,iter=100):
    weights,X = self.initialize(X)
#cost function:
    def cost(theta):
      z=dot(X,theta)
      cost0=y.T.dot(log(self.sigmoid(z)))
      cost1=(1-y).T.dot(log(1-self.sigmoid(z)))
      cost=-((cost1+cost0))/len(y)
      return cost
    cost_list = np.zeros(iter,)
    for i in range(iter):
      weights = weights - alpha * dot(X.T, self.sigmoid(dot(X,weights)) - np.reshape(y,(len(y),1)))
      cost_list[i] = cost(weights)
    self.weights = weights
    return cost_list
#predict:
  def predict(self,X):
    z=dot(self.initialize(X)[1],self.weights)
    lis=[]
    for i in self.sigmoid(z):
      if i>0.5:
        lis.append(1)
      else:
        lis.append(0)
    return lis

In [77]:
#f1score:
def f1_score(y,y_hat):
  tp,tn,fp,fn=0,0,0,0
  for i in range(len(y)):
    if y[i]==1 and y_hat[i]==1:
     tp=tp+1
    elif y[i]==1 and y_hat[i]==0:
     fn=fn+1
    elif y[i]==0 and y_hat[i]==1:
     fp=fp+1
    elif y[i]==0 and y_hat[i]==0:
     tn=tn+1 
  precision=tp/(tp+fp)
  recall=tp/(tp+fn)
  f1_score=2*precision*recall/(precision+recall)
  return f1_score

In [78]:
#calling:
standardize(x_train)
standardize(x_test)
obj1=LogidticRegression()
model=obj1.fit(x_train,y_train)
y_predict=obj1.predict(x_test)
y_tr=obj1.predict(x_train)

f1_score_traing=f1_score(y_train,y_tr)
f1_score_test=f1_score(y_test,y_predict)
print("F1 Score of Training:",f1_score_traing)
print("F1 Score of Testing:",f1_score_test)

F1 Score of Training: 0.9278350515463919
F1 Score of Testing: 0.888888888888889


In [79]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
model=LogisticRegression().fit(x_train,y_train)
y_pre=model.predict(x_test)
y_tr=model.predict(x_train)

print("F1 Score of Training:",f1_score(y_train,y_tr))
print("F1 Score of Testing:",f1_score(y_test,y_pre))

F1 Score of Training: 0.9361702127659574
F1 Score of Testing: 0.888888888888889
